### ISSUE TITLE
I need an FW

### ISSUE THREAD

**Issue by stefanbeier** [neoxic/ESCape32#10]
I need a Bootloader and a FW for an AT32F421K8U7 MCU with signal line on PB4.
Were can i find it?
Now the ESC run with AM32_TEKKO_F421 1.98.

**Comment by neoxic** [comment]
Signal line on PB4 is not supported on the AT32F421, sorry. You can make your ESC compatible by connecting PB4 and PA2 with a shunt.

**Comment by neoxic** [comment]
https://github.com/neoxic/ESCape32/wiki

**Comment by neoxic** [comment]
The shunt can be any tiny wire that connects two pins - PA2 and PB4. I would use a braid from a 16 AWG wire or something.

**Comment by neoxic** [comment]
![image](https://github.com/user-attachments/assets/c7e86343-f0ac-4180-96e0-ddff564fee5e)

**Comment by stefanbeier** [comment]
A bridge between PA2 and PB4 was unsuccessful. The signal line directly on PA2 works. Can I leave the signal line directly on PA2, or should I build a resistor into the line? I measure 120 ohms between BP4 and the signal line on the ESC connector. Is the signal from the signal line processed at another point in the ESC layout, or is it only connected to the pin on the MCU?

**Comment by stefanbeier** [comment]
I installed the FW Airbot1. But I don't know if it's the right one. It makes the motor rotate and I can change the ESC settings via WiFi. Can I assume that it's the right FW? What would happen if it's not the right firmware?

**Comment by neoxic** [comment]
> A bridge between PA2 and PB4 was unsuccessful. The signal line directly on PA2 works. Can I leave the signal line directly on PA2, or should I build a resistor into the line? I measure 120 ohms between BP4 and the signal line on the ESC connector.

It's advised to have a series resistor. You can see on the picture that I connected PA2 to the series resistor on the signal line (that is also connected to PB4). You can do the same to reuse the same resistor. Your shunt was unsuccessful because AIRBOT1 uses PB4 for LED control, i.e. there's a conflict. If AIRBOT1 works for, you can use NEUTRONRC2 instead (it's a generic target that doesn't use any other pins except for the mandatory ones), hence your shunt will work (there will be no conflict with PB4).

> Is the signal from the signal line processed at another point in the ESC layout, or is it only connected to the pin on the MCU?

I guess that's what you mean... AIRBOT1 uses PB4 as one of the LED control lines. Use NEUTRONRC2 instead.

**Comment by neoxic** [comment]
> I installed the FW Airbot1. But I don't know if it's the right one. It makes the motor rotate and I can change the ESC settings via WiFi. Can I assume that it's the right FW? What would happen if it's not the right firmware?

If it's not the right firmware, the motor will not spin properly. But there are cases when there can be damage to the ESC if for example mosfet control logic is inverted. At present, there is only one image that can cause such damage - NEUTRONRC4. It's explicitly marked in the wiki.

**Comment by stefanbeier** [comment]
Thank you very much for your help. The NEUTRONRC2 firmware also works with the bridge between PA2 and PB4. Just as you wrote. But unfortunately I don't get any voltage or current as telemetry data. Other inputs of the MCU are probably being used. The AIRBOT1 got the current value, but the voltage value was not true.

**Comment by neoxic** [comment]
NEUTRONRC2 is a generic target, i.e. it doesn't have voltage/current telemetry, LED control, etc. Feel free to hop into our discord server (the link is in the wiki), post close up pictures of your ESC, and we'll figure out the rest should you need that. A new target might be needed for your ESC with a _"converted to PA"_ remark as usual.

**Comment by stefanbeier** [comment]
Is the telemetry output on the Airbot1 FW also on pin PB6? It is wired like this on my ESC. But no data is received by Frsky. S.PORT is selected. But I can see telemetry data via WiFi.
