### ISSUE TITLE
Support for SEQURE SQESC 12200

### ISSUE THREAD

**Issue by jasc76** [neoxic/ESCape32#12]
Hi there

you support the 28100, Any plans for the 12200 ??

Regards
Jan

**Comment by neoxic** [comment]
You can try using the SEQURE2 target for it although the current sensing will produce incorrect readings. The ball is on the Sequre side. They've been working on that as far as I know.

**Comment by neoxic** [comment]
You can recompile the SEQURE2 target with a different `CURR_MUL` value to make the current readings correct. I just still don't know their actual current sensor multiplier.
