### ISSUE TITLE
VTOL motor positioning on stop

### ISSUE THREAD

**Issue by okiaba** [neoxic/ESCape32#4]
Hi there, awesome work!
This is a feature request or more even a feature possibility request.

I'm looking for a way to align VTOL Quadplane Motors in flight when they are stopped. (like this: https://youtu.be/rsTkrPtcVTk?t=34) From my understanding this should be possible with a simple hall sensor+magnet (on/off input) and some software tweaks to have a slow turning movement until the hall sensor is reached?

There are very few ESCs that have this capability and none of them fit my criterias, bringing this feature to ESCape32 would be a huge win for the VTOL community, as there so much more Hardware available.

What do you think? Would such a feature be at all be possible and/or of your interest?

Thanks!

**Comment by neoxic** [comment]
Please feel free to join our Discord server for feature requests and real time discussions.
