### ISSUE TITLE
Feature request: brake function for plane

### ISSUE THREAD

**Issue by robustini** [neoxic/ESCape32#7]
It would be interesting to have the brake feature, which is very useful on plane.
Obviously it will consume power but in many contexts it is a necessity to be able to keep the propeller stationary at zero throttle while the plane is in flight.

**Comment by neoxic** [comment]
Does 100% passive brake (`duty_drag=100`) work in your case? I also have plans to implement a feature called "motor lock" in the upcoming revision. It will work as active brake by consuming some power.
