### ISSUE TITLE
Use serial mode to adjust parameters instead of using the command line CLI.

### ISSUE THREAD

**Issue by Linjieqiang** [neoxic/ESCape32#9]
![image](https://github.com/user-attachments/assets/404eb73f-3b50-4b90-8319-ceb72e0b0907)

Now we can control the motor through the serial port, can we set up a protocol to adjust the motor parameters? Not use the cli command. @neoxic 

- Byte0: 0xFF (mean adjust the params)
- Byte1: which param? 
    - arm: 0x01
    - damp: 0x02
    - revdir: 0x03
    - brushed: 0x04
    - .....
- Byte2: param value
- Byte3: crc8

**Comment by neoxic** [comment]
I don't think I'll ever go down that path for several reasons:

1) This serial protocol is not designed for configuration. You don't get confirmations to your commands to make sure they're correct. It's kind of a serial version of DSHOT with some extensions.

2) It's a duplicate functionality. If you want to enter configuration mode (CLI), switch your baud rate to 38400, wait for ~2s and there you go. When you're done, send a break character (or bootloader probe) and switch back.

3) It will be hard to maintain binary compatibility in case some parameters get added/changed/removed in the future.
